#ifndef FACTORY_EXPERIMENTS_COMPONENTMEMORYLAYER_HPP
#define FACTORY_EXPERIMENTS_COMPONENTMEMORYLAYER_HPP


/*!
\file
\brief ${BRIEF_FILE_DESCRIPTION}
*/

class ComponentMemoryLayer {

};


#endif //FACTORY_EXPERIMENTS_COMPONENTMEMORYLAYER_HPP
