#ifndef FACTORY_EXPERIMENTS_MACROS_HPP
#define FACTORY_EXPERIMENTS_MACROS_HPP

#define TOTAL_POSSIBLE_COMPONENTS 6

#define DEFAULT_RESERVED_SPACE_FOR_COMPONENTS 2


#endif //FACTORY_EXPERIMENTS_MACROS_HPP
