#ifndef FACTORY_EXPERIMENTS_MACROS_HPP
#define FACTORY_EXPERIMENTS_MACROS_HPP

#define TOTAL_POSSIBLE_COMPONENTS 7

#define INITIAL_RESERVED_SPACE_FOR_COMPONENTS 2


#endif //FACTORY_EXPERIMENTS_MACROS_HPP
